In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x = tf.constant([[1,2],[3,4],[5,6]])

y = tf.constant([[7,8],[9,10],[11,12]])



In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

## Dot product

In [ ]:
tf.tensordot(tf.transpose(x),y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(x,tf.transpose(y),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

## Changing the data type

In [ ]:

b = tf.constant([1.7,7.1])

c = tf.constant([1,7])

b,c

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.1], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
b = tf.cast(b,dtype = tf.float16)

In [ ]:
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.1], dtype=float16)>

In [ ]:
c = tf.cast(c, dtype = tf.int16)

In [ ]:
c

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

## Getting the absolute values

In [ ]:
d = tf.constant([-7,-11])

d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -11], dtype=int32)>

In [ ]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 11], dtype=int32)>

## Finding the mean, min, max, sum

In [ ]:
element = tf.constant(np.random.randint(low = 0,high = 100,size = 50))
element

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([63, 58, 49, 31, 55,  5, 73,  9, 32, 67, 32, 12, 75, 19, 29, 34, 42,
       93,  5,  8, 86, 70, 38, 50, 51, 37, 88, 74, 44, 77, 72, 86, 93, 34,
       27, 86, 15,  5, 22, 47, 31, 15, 10, 99,  5, 68, 96, 70, 29, 13])>

In [ ]:
tf.reduce_min(element)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
tf.reduce_max(element)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(element)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
tf.reduce_sum(element)

<tf.Tensor: shape=(), dtype=int64, numpy=2329>

## finding the positional maximum and minimum element

In [ ]:
element

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([63, 58, 49, 31, 55,  5, 73,  9, 32, 67, 32, 12, 75, 19, 29, 34, 42,
       93,  5,  8, 86, 70, 38, 50, 51, 37, 88, 74, 44, 77, 72, 86, 93, 34,
       27, 86, 15,  5, 22, 47, 31, 15, 10, 99,  5, 68, 96, 70, 29, 13])>

In [ ]:
tf.argmax(element)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
tf.argmin(element)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

## Squeezing the tensor (removing all single dimensions)

In [ ]:
element = tf.constant(np.random.randint(0,100,50),shape =(1,1,1,1,50))

element

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[28, 57, 36, 17, 12, 41, 74, 37, 57, 90, 23, 49, 81, 19, 73,
           63, 38, 99, 98, 88, 27, 16, 70, 25, 72, 25, 20, 82, 50, 56,
           16, 52, 20, 66, 48, 52,  4, 60, 82, 93, 95, 90, 77, 43, 60,
           55, 44, 63,  5, 57]]]]])>

In [ ]:
element[0][0][0][0][0]

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [ ]:
element.shape,element.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
element_squ = tf.squeeze(element)

element_squ.shape,element_squ.ndim

(TensorShape([50]), 1)

In [ ]:
element_squ

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([28, 57, 36, 17, 12, 41, 74, 37, 57, 90, 23, 49, 81, 19, 73, 63, 38,
       99, 98, 88, 27, 16, 70, 25, 72, 25, 20, 82, 50, 56, 16, 52, 20, 66,
       48, 52,  4, 60, 82, 93, 95, 90, 77, 43, 60, 55, 44, 63,  5, 57])>

## One hot encoding

In [ ]:
list1 = [0,1,2,3]

tf.one_hot(list1,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## squaring, log, square root

In [ ]:
element = tf.constant(np.arange(1,10))

element

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(element)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
tf.sqrt(element)

InvalidArgumentError: ignored

In [ ]:
tf.sqrt(tf.cast(element,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
h = tf.cast(element,dtype = tf.float32)

In [ ]:
tf.math.log(h)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating the tensor tf.variable

In [ ]:
element = tf.Variable(np.arange(0,5))

In [ ]:
element

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
element.assign([0,1,2,3,40])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 40])>

In [ ]:
element

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 40])>

In [ ]:
element.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 50])>

In [ ]:
element.assign_sub([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 40])>

# Tensor & Numpy

In [ ]:
element = tf.constant(np.array([1,2,3,4,5,6,7]))

element

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7])>

In [ ]:
np.array(element),type(np.array(element))

(array([1, 2, 3, 4, 5, 6, 7]), numpy.ndarray)

In [ ]:
element.numpy(),type(element.numpy())

(array([1, 2, 3, 4, 5, 6, 7]), numpy.ndarray)

## Finding the access of GPU

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
## AFTER CONNECTING TO GPU

import tensorflow as tf
import numpy as np
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
