## Shuffled


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# shuffled on axis = 0

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle but in same order

# set global random seed
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## multiple ways to create tensors

In [ ]:
tf.ones(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.ones(shape = (3,3,2))

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
numpy_array = np.arange(1,65,dtype = "int32")

a = tf.constant(numpy_array,shape = [4,4,4])

numpy_array,a

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], dtype=int32),
 <tf.Tensor: shape=(4, 4, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],
 
        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]],
 
        [[49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]]], dtype=int32)>)

In [ ]:
a.ndim

3

In [ ]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
print("DATA TYPE OF EVERY ELEMENT IS : ",rank_4_tensor.dtype)
print("NUMBER OF DIMENSIONS PRESENT : ",rank_4_tensor.ndim)
print("SHAPE OF TENSOR : ",rank_4_tensor.shape)
print("SHAPE OF TENSOR : ",rank_4_tensor.shape[0])
print("SHAPE OF TENSOR : ",rank_4_tensor.shape[-1])
print("TOTAL NUMBER OF ELEMENTS PRESENT IN RANK_4_TENSOR : ",tf.size(rank_4_tensor).numpy())

DATA TYPE OF EVERY ELEMENT IS :  <dtype: 'float32'>
NUMBER OF DIMENSIONS PRESENT :  4
SHAPE OF TENSOR :  (2, 3, 4, 5)
SHAPE OF TENSOR :  2
SHAPE OF TENSOR :  5
TOTAL NUMBER OF ELEMENTS PRESENT IN RANK_4_TENSOR :  120


In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# lets create a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
2*2 4
2*2*1 4

## EXPAND_DIMS

In [ ]:
tf.expand_dims(rank_2_tensor,axis = -1)  # -1 means last axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# lets create a rank 2 tensor

rank_2 = tf.constant([[[[10,7],
                        [3,4]]]])

rank_2

<tf.Tensor: shape=(1, 1, 2, 2), dtype=int32, numpy=
array([[[[10,  7],
         [ 3,  4]]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2,axis = -1)  # -1 means last axis


<tf.Tensor: shape=(1, 1, 2, 2, 1), dtype=int32, numpy=
array([[[[[10],
          [ 7]],

         [[ 3],
          [ 4]]]]], dtype=int32)>

In [ ]:
rank_2[0][0][0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
tf.ones(shape = [2,2,2,3])

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

## Manipulating tensors

In [ ]:
tensor = tf.constant([[10,7],
                      [3,4]])

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## Addition

In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor =  tensor + 10

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# substraction

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor = tensor - 10

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]

list1+list2

[1, 2, 3, 4, 5, 6]

In [ ]:
# works in elemental level (array,tensor)

array_1 = np.array(list1)
array_2 = np.array(list2)

array_1+array_2

array([5, 7, 9])

##MULTIPLICATION

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# always use matmul operation for matrix multiplication

tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

y = tf.constant([[7,8],
                 [9,10],
                  [11,12]])

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
x @ y

# difference of shape


InvalidArgumentError: ignored

In [ ]:
y_1 = tf.reshape(y,shape = (2,3))

In [ ]:
x @ y_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x.shape,y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
x @ tf.transpose(y_1)

InvalidArgumentError: ignored