## Tensorflow

In [ ]:
"""

What is TensorFlow

TensorFlow is an open source end to end machine learning library used for preprocessing data, modelling.

Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as TensorFlow.
This is because it contains many of the most common machine learning functions you'll want to use

"""

In [ ]:
"""

The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that
tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to
find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

"""

In [ ]:
# import the libraby

import tensorflow as tf

In [ ]:
# see the versions of tensorflow

print(tf.__version__)    # should be always grreater than 2

2.13.0


# Creating the Tensors by our own

## Scalar

In [ ]:
scalar = tf.constant(11)

In [ ]:
scalar

In [ ]:
# a scalar is known as rank 0 tensor. because it is having no dimensions its just a Number

scalar.ndim

0

## Vector

In [ ]:
vector = tf.constant([1,2,3,4])

vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
vector.ndim

1

## Matrix

In [ ]:
matrix = tf.constant([[1,2],
                      [3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# checking the dimension of matrix

matrix.ndim

2

In [ ]:
matrix_1 = tf.constant([[1.1,2.1],
                      [3.1,4.1]])

matrix_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1, 2.1],
       [3.1, 4.1]], dtype=float32)>

In [ ]:
matrix_1.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
"""

saclar : a single number
vector : a number with direction
matrix : its 2 dimensional array of numbers
tensor : an n-dimensional array of numbers

""""

## TF.VARIABLE

In [ ]:
variable = tf.Variable([10,20])

constant = tf.constant([10,20])


In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
constant

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
variable[0] = 100

"""

TypeError                                 Traceback (most recent call last)
<ipython-input-23-8a2d6c04a1a3> in <cell line: 1>()
----> 1 variable[0] = 100

TypeError: 'ResourceVariable' object does not support item assignment

"""

TypeError: ignored

In [ ]:
"""

string = "a"   memory less   10kb
list_1 = [1,2,3]  memory high 15kb

"""

## .Assign method

In [ ]:
variable[0].assign(100)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([100,  20], dtype=int32)>

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,  20], dtype=int32)>

In [ ]:
constant[0] = 100

"""
TypeError                                 Traceback (most recent call last)
<ipython-input-29-f291bab9ca00> in <cell line: 1>()
----> 1 constant[0] = 100

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

"""

TypeError: ignored

In [1]:
constant[0].assign(100)

"""

AttributeError                            Traceback (most recent call last)
<ipython-input-30-48b7dab7247b> in <cell line: 1>()
----> 1 constant[0].assign(100)

/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py in __getattr__(self, name)
    428         np_config.enable_numpy_behavior()
    429       """)
--> 430     self.__getattribute__(name)
    431
    432   @property

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign

"""

SyntaxError: ignored

## Creating an random Number

In [ ]:
random_tensor = tf.random.Generator.from_seed(42)

random_tensor = random_tensor.normal(shape=(3,2))

random_tensor_1 = tf.random.Generator.from_seed(42)

random_tensor_1 = random_tensor_1.normal(shape = (3,2))


In [ ]:
random_tensor,random_tensor_1,random_tensor==random_tensor_1


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_tensor = tf.random.Generator.from_seed(10)

random_tensor = random_tensor.normal(shape=(3,2))

random_tensor_1 = tf.random.Generator.from_seed(24)

random_tensor_1 = random_tensor_1.normal(shape = (3,2))


In [ ]:
random_tensor,random_tensor_1,random_tensor==random_tensor_1


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)